name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - uses: dotnet/nbgv@master
      with:
        setAllVars: true

#     - name: Test
#       run: go test -v ./...        

    - name: Build
      run: |
        for GOOS in "windows" "linux" "darwin"
        do
            for GOARCH in "amd64" "arm64"
            do
                CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build
                if [ $GOOS == "windows" ]
                then
                    zip FabricPing_${GOOS}_${GOARCH}.zip FabricPing.exe
                else
                    tar czf FabricPing_${GOOS}_${GOARCH}.tar.gz FabricPing
                fi
            done
        done
        
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
      run: |
        gh release create v$NBGV_SimpleVersion *.tar.gz *.zip
