name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - uses: dotnet/nbgv@master
      with:
        setAllVars: true

#     - name: Test
#       run: go test -v ./...        

    - name: Build Linux
      if: runner.os != 'Windows'
      run: |
        CGO_ENABLED=0 go build -ldflags "-X main.mainver=$NBGV_SimpleVersion" -v ./...

    - name: Pack Linux
      if: runner.os != 'Windows'
      run: |
        tar czf FabricPing_linux_x64.tar.gz FabricPing

    - name: Upload a Build Artifact
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v2
      with:
        path: FabricPing_linux_x64.tar.gz

    - name: Build Windows
      if: runner.os == 'Windows'
      run: |
        go build -ldflags "-X main.mainver=$env:NBGV_SimpleVersion" -v ./...

    - name: E2E Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        powershell "$env:ProgramFiles\Microsoft SDKs\Service Fabric\ClusterSetup\DevClusterSetup.ps1" -AsSecure -Auto
        if ((.\FabricPing.exe -d 127.0.0.1:19002 | sls NodePhaseRouting | measure).Count -ne 5) { exit 1}

    - name: Pack Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Compress-Archive .\FabricPing.exe .\FabricPing_win_x64.zip

    - name: Upload a Build Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        path: FabricPing_win_x64.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      
    - uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        gh release create v$NBGV_SimpleVersion artifact/*
    
