name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [windows, linux, darwin]
        GOARCH: [arm64, amd64]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - uses: dotnet/nbgv@master
      with:
        setAllVars: true

#     - name: Test
#       run: go test -v ./...        

    - name: Build
      run: |
        mkdir -p ${{ matrix.GOOS }}/${{ matrix.GOARCH }}
        CGO_ENABLED=0 GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} go build -ldflags "-X main.mainver=$NBGV_SimpleVersion" -v ./... -o ${{ matrix.GOOS }}/${{ matrix.GOARCH }}/FabricPing
        cd ${{ matrix.GOOS }}/${{ matrix.GOARCH }}
        tar czf FabricPing_${{ matrix.GOOS }}_${{ matrix.GOARCH }}.tar.gz *
        
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
      run: |
        mkdir release
        find . -name *.tar.gz -exec mv {} release/ \;
        gh release create v$NBGV_SimpleVersion release/*
